modLoader="javafml"
loaderVersion="[1,)" # Forge version range
license="MIT"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="Example Mod"
description="A simple example mod for Minecraft 1.21.10"
